# Generated by Django 3.2 on 2021-04-10 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Отправлено')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение анонима',
                'verbose_name_plural': 'Сообщения анонимов',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=4, verbose_name='Год окончания')),
                ('category', models.CharField(choices=[('Высшее образование', 'Высшее образование'), ('Курсы', 'Повышение квалификации, курсы')], max_length=255, verbose_name='Тип обучения')),
                ('place', models.CharField(max_length=255, verbose_name='Место обучения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-grad_year'],
            },
        ),
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Место работы')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Начало работы')),
                ('end_date', models.DateField(blank=True, help_text='Оставьте поле пустым чтобы получить значение "По настоящее время"', null=True, verbose_name='Окончание работы')),
                ('responsibilities', models.TextField(verbose_name='Описание обязанностей')),
                ('company_web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сайт компании')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя отправителя')),
                ('email', models.EmailField(db_index=True, help_text='Электронная почта', max_length=255)),
                ('company', models.CharField(blank=True, help_text='Не обязательно', max_length=255, null=True, verbose_name='Компания пользователя')),
                ('phone', models.CharField(blank=True, help_text='Не обязательно', max_length=50, null=True, verbose_name='Телефон')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cv_app.anonymousmessage', verbose_name='Сообщения пользователя')),
            ],
            options={
                'verbose_name': 'Анонимный пользователь',
                'verbose_name_plural': 'Анонимные пользователи',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cv_app.anonymoususer', verbose_name='Отправитель'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('email', models.EmailField(db_index=True, help_text='Почта для связи с Вами.', max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=200, verbose_name='Ваше имя')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ваша фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Работодатель',
                'verbose_name_plural': 'Работодатели',
                'ordering': ['-registration_date'],
            },
        ),
    ]
