# Generated by Django 3.1.7 on 2021-02-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Место работы')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('start_date', models.DateField(verbose_name='Начало работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание работы')),
                ('description', models.TextField(verbose_name='Описание обязанностей')),
                ('company_web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сайт компании')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
    ]
