# Generated by Django 3.1.7 on 2021-03-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingexperience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Оставьте поле пустым чтобы получить значение "По настоящее время"', null=True, verbose_name='Окончание работы'),
        ),
    ]
