# Generated by Django 3.1.7 on 2021-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20210414_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=255, verbose_name='Имя записи')),
                ('about_me_text', models.TextField(blank=True, null=True, verbose_name='Обо мне')),
                ('active', models.BooleanField(default=False, verbose_name='Активная')),
                ('fall_back', models.BooleanField(default=False, verbose_name='Резервная')),
                ('made_on', models.DateField(auto_now=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
    ]

#6
