# Generated by Django 3.1.7 on 2021-04-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_app', '0002_auto_20210303_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grad_year', models.CharField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], max_length=4, verbose_name='Год окончания')),
                ('category', models.CharField(choices=[('higher_education', 'Высшее образование'), ('course', 'Повышение квалификации, курсы')], max_length=255, verbose_name='Тип обучения')),
                ('place', models.CharField(max_length=255, verbose_name='Место обучения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-grad_year'],
            },
        ),
        migrations.RenameField(
            model_name='workingexperience',
            old_name='description',
            new_name='responsibilities',
        ),
    ]
