# Generated by Django 3.1.7 on 2021-04-01 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210401_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(auto_now=True, verbose_name='Дата отправки')),
                ('read_or_not', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('title', models.CharField(blank=True, default='Без темы', max_length=255, null=True, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст Сообщения')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_user_compasny', to=settings.AUTH_USER_MODEL, verbose_name='Компания отправителя')),
                ('sender_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_customuser', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-message_date'],
            },
        ),
    ]
