# Generated by Django 3.1.7 on 2021-04-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='sender_company',
        ),
    ]
